# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

use_frameworks!

target 'TracksDemo' do
  pod 'Automattic-Tracks-iOS', :path => '../'

  target 'TracksDemoTests' do

  end
end

