# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

target 'TracksDemo' do
  pod 'Automattic-Tracks-iOS', :path => '../'
end

target 'TracksDemoTests' do

end

