# frozen_string_literal: true

# Uncomment this line to define a global platform for your project
use_frameworks!

target 'TracksDemo' do
  platform :ios, '13.0'

  pod 'Automattic-Tracks-iOS', path: '../'
end

target 'TracksDemo Mac' do
  platform :osx, '10.15'

  pod 'Automattic-Tracks-iOS', path: '../'
end
