# Opt in to new cops by default
AllCops:
  NewCops: enable
  Exclude:
    # Notice the `./**/` to handle `DerivedData` in root and subfolders (`./TracksDemo`)
    - ./**/DerivedData/**/*
    # As of 2026/01, CocoaPods is no longer in use.
    # Leaving here for the time being to avoid false positives on local checkouts.
    - Pods/**/*
    - build/**/*
    - vendor/**/*


# Override the maximum line length
Layout/LineLength:
  Max: 160
