# references:
# https://github.com/CocoaPods/pod-template/blob/master/.travis.yml

osx_image: xcode9.4
language: objective-c
xcode_workspace: Automattic-Tracks-iOS.xcworkspace
xcode_scheme: Automattic-Tracks-iOS
xcode_sdk: iphonesimulator
# podfile: Example/Podfile
before_install:
 - gem install cocoapods # Since Travis is not always on latest version
 - pod repo update --silent && pod install
script:
- Scripts/build.sh