install:
- pod repo update --silent && pod install
osx_image: xcode7.3
language: objective-c
xcode_workspace: Automattic-Tracks-iOS.xcworkspace
xcode_scheme: Automattic-Tracks-iOS
xcode_sdk: iphonesimulator

