version: 2.1

orbs:
  # Using 1.0 of our Orbs means it will use the latest 1.0.x version from https://github.com/wordpress-mobile/circleci-orbs
  ios: wordpress-mobile/ios@1.0

workflows:
  test_and_validate:
    jobs:
      - ios/test:
          name: Test
          workspace: Automattic-Tracks-iOS.xcworkspace
          xcode-version: "11.2.1"
          scheme: Automattic-Tracks-iOS
          device: iPhone 11
          ios-version: "13.2.2"
          bundle-install: true
          pod-install: true
      - ios/validate-podspec:
          name: Validate Podspec
          podspec-path: Automattic-Tracks-iOS.podspec
          bundle-install: true
      - ios/publish-podspec:
          name: Publish pod to Trunk
          xcode-version: "11.2.1"
          podspec-path: Automattic-Tracks-iOS.podspec
          bundle-install: true
          post-to-slack: true
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
