version: 2.1

orbs:
  # Using 1.0 of our Orbs means it will use the latest 1.0.x version from https://github.com/wordpress-mobile/circleci-orbs
  ios: wordpress-mobile/ios@1.0

jobs:
  TestIOS:
    executor:
      name: ios/default
      xcode-version: "12.0.0"
    steps:
      - checkout
      - ios/install-dependencies:
          bundle-install: true
          pod-install: true
      - run:
          name: Build and Test
          command: |
            # Create the log directory
            mkdir -p logs

            # Build without code signing to avoid missing cert errors
            xcodebuild COMPILER_INDEX_STORE_ENABLE=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO \
                       -workspace 'Automattic-Tracks-iOS.xcworkspace' \
                       -scheme 'Automattic-Tracks-iOS' \
                       -destination 'platform=iOS Simulator,name=iPhone 11' \
                       test  | tee logs/build-and-test.log | xcpretty -r junit
  TestMacOS:
    executor:
      name: ios/default
      xcode-version: "12.0.0"
    steps:
      - checkout
      - ios/install-dependencies:
          bundle-install: true
          pod-install: true
      - run:
          name: Build and Test
          command: |
            # Create the log directory
            mkdir -p logs

            # Build without code signing to avoid missing cert errors
            xcodebuild COMPILER_INDEX_STORE_ENABLE=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO \
                       -workspace 'Automattic-Tracks-iOS.xcworkspace' \
                       -scheme 'Automattic-Tracks-OSX' \
                       -destination 'platform=OS X,arch=x86_64' \
                       test  | tee logs/build-and-test.log | xcpretty -r junit

workflows:
  test_and_validate:
    jobs:
      - TestIOS:
          name: Test iOS
      # Disabled due to issues on Xcode 12
      # - ios/validate-podspec:
      #     name: Validate Podspec
      #     xcode-version: "12.0.0"
      #     podspec-path: Automattic-Tracks-iOS.podspec
      #     bundle-install: true
      - ios/publish-podspec:
          name: Publish pod to Trunk
          xcode-version: "12.0.0"
          podspec-path: Automattic-Tracks-iOS.podspec
          bundle-install: true
          post-to-slack: true
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - TestMacOS:
          name: "Test macOS"
