version: 2.1

orbs:
  # Using 1.0 of our Orbs means it will use the latest 1.0.x version from https://github.com/wordpress-mobile/circleci-orbs
  ios: wordpress-mobile/ios@1.0

jobs:
  TestiOS:
    executor:
      name: ios/default
      xcode-version: "12.5.0"
    steps:
      - checkout
       # Start: Swift Package Manager Workaround
      # Ref. https://support.circleci.com/hc/en-us/articles/360044709573-Swift-Package-Manager-fails-to-clone-from-private-Git-repositories
      - run: 
          name: Swift Package Manager workaround
          command: for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts || true
      # END: Swift Package Manager Workaround
      - ios/test:
          xcode-version: "12.5.0"
          scheme: AutomatticTracksiOS
          device: iPhone 11
          ios-version: "14.0"
          bundle-install: false
          pod-install: false
          
  TestMacOS:
    executor:
      name: ios/default
      xcode-version: "12.5.0"
    steps:
      - checkout
      # Start: Swift Package Manager Workaround
      # Ref. https://support.circleci.com/hc/en-us/articles/360044709573-Swift-Package-Manager-fails-to-clone-from-private-Git-repositories
      - run: 
          name: Swift Package Manager workaround
          command: for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts || true
      # END: Swift Package Manager Workaround
      - run:
          name: Build and Test
          command: |
            # Create the log directory
            mkdir -p logs

            # Build without code signing to avoid missing cert errors
            xcodebuild COMPILER_INDEX_STORE_ENABLE=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO \
                       -scheme 'AutomatticTracksiOS' \
                       -destination 'platform=OS X,arch=x86_64' \
                       test  | tee logs/build-and-test.log | xcpretty -r junit
  CheckVersionConsistency:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: Check pod version consistency
          command: |
            SRC_FILE=Sources/Model/ObjC/TracksConstants.m
            PODSPEC_FILE=Automattic-Tracks-iOS.podspec

            SOURCE_VERS=$(sed -n s/'^.* TracksLibraryVersion = @"\(.*\)";.*$'/'\1'/p $SRC_FILE)
            POD_VERS=$(sed -n s/'^ *s.version *= \([^ ]*\).*$'/'\1'/p $PODSPEC_FILE | tr -d \'\")
            
            echo Version found in $SRC_FILE: $SOURCE_VERS
            echo Version found in $PODSPEC_FILE: $POD_VERS
            if [ "$SOURCE_VERS" = "$POD_VERS" ]; then
              echo "Version values match :)"
            else
              echo "Version values differ! Please fix by making sure the 2 files have matching values for the version."
              exit 1
            fi

workflows:
  test_and_validate:
    jobs:
      - ios/validate-podspec:
          name: Validate Podspec
          xcode-version: "12.5.0"
          podspec-path: Automattic-Tracks-iOS.podspec
          bundle-install: true
          update-specs-repo: true
          # Event though `update-specs-repo` is true, the command looks like
          # it's not running propertly in CI as it takes only one 1s and the
          # Sodium-Fork spec is not found.
          #
          # See:
          # - https://app.circleci.com/pipelines/github/Automattic/Automattic-Tracks-iOS/383/workflows/4989ecc1-ed24-4b74-8574-cf68524613ac/jobs/947
          # - https://app.circleci.com/pipelines/github/Automattic/Automattic-Tracks-iOS/382/workflows/4fab7fd2-6cbd-4bc0-b7d1-052cde1d5698/jobs/944
          #
          # To work around that issue, look for Sodium-Fork in a secondary
          # source.
          sources: "https://cdn.cocoapods.org/"
      - ios/publish-podspec:
          name: Publish pod to Trunk
          xcode-version: "12.5.0"
          podspec-path: Automattic-Tracks-iOS.podspec
          bundle-install: true
          post-to-slack: true
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - CheckVersionConsistency:
          name: "Validate Version Values Consistency"
      - TestMacOS:
          name: "Test macOS"
      - TestiOS:
          name: "Test iOS"
