version: 2.1

orbs:
  # This uses the iOS Orb located at https://github.com/wordpress-mobile/circleci-orbs
  ios: wordpress-mobile/ios@0.0.17

workflows:
  test_and_validate:
    jobs:
      - ios/test:
          name: Test
          workspace: Automattic-Tracks-iOS.xcworkspace
          scheme: Automattic-Tracks-iOS
          device: iPhone XS
          ios-version: "12.1"
      - ios/validate-podspec:
          name: Validate Podspec
          podspec-path: Automattic-Tracks-iOS.podspec
