# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

agents:
  queue: mac

env:
  IMAGE_ID: $IMAGE_ID

# This is the default pipeline – it will build and test the app
steps:
  ######################
  # Build and Test iOS
  ######################
  - label: "🧪 Build and Test iOS"
    key: test_ios
    command: |
      install_gems
      bundle exec fastlane ios test clean:true
    plugins: [$CI_TOOLKIT_PLUGIN]
    artifact_paths: .build/logs/*.log

  - label: "🧪 ExPlat Thread Sanitizer"
    key: test_explat_tsan
    command: |
      install_gems
      bundle exec fastlane ios test_explat_concurrency_tsan clean:true
    plugins: [$CI_TOOLKIT_PLUGIN]
    artifact_paths: .build/logs/*.log

  ######################
  # Build and Test macOS
  ######################
  - label: "🧪 Build and Test macOS"
    key: test_macos
    command: |
      install_gems
      bundle exec fastlane mac test clean:true
    plugins: [$CI_TOOLKIT_PLUGIN]
    artifact_paths: .build/logs/*.log

  - label: ":swift: SwiftLint"
    command: swiftlint
    agents:
      queue: linter
