# Nodes with values to reuse in the pipeline.
common_params:
  plugins: &common_plugins
  - &bash_cache automattic/bash-cache#2.8.0
  # Common environment values to use with the `env` key.
  env: &common_env
    IMAGE_ID: xcode-13.4.1

# This is the default pipeline – it will build and test the app
steps:
  ######################
  # Build and Test iOS
  ######################
  - label: "🧪 Build and Test iOS"
    key: "test_ios"
    command: |
      # Build and test the pod twice if needed. This is necessary under Xcode 12 to avoid an error
      # that occurs the first time after cleaning if one of your dependences uses a binary framework
      # See https://bugs.swift.org/browse/SR-13803

      build_and_test_pod ios test || build_and_test_pod ios test
    env: *common_env
    plugins: *common_plugins
    artifact_paths: ".build/logs/*.log"

  ######################
  # Build and Test macOS
  ######################
  - label: "🧪 Build and Test macOS"
    key: "test_macos"
    command: |
      # Build and test the pod twice if needed. This is necessary under Xcode 12 to avoid an error
      # that occurs the first time after cleaning if one of your dependences uses a binary framework
      # See https://bugs.swift.org/browse/SR-13803

      build_and_test_pod mac test || build_and_test_pod mac test
    env: *common_env
    plugins: *common_plugins
    artifact_paths: ".build/logs/*.log"

  #################
  # Validate Podspec
  #################
  - label: "🔬 Validating Podspec"
    key: "validate"
    command: |
      validate_podspec
    env: *common_env
    plugins: *common_plugins
    artifact_paths: ".build/logs/*.log"

  #################
  # Check Version Consistency
  #################
  - label: "🔬 Validating Version"
    key: "version_check"
    command: .buildkite/check-version-consistency.sh
    env: *common_env
    plugins: *common_plugins

  #################
  # Lint
  #################
  - label: "🧹 Lint"
    key: "lint"
    command: |
      lint_pod
    env: *common_env
    plugins: *common_plugins

  #################
  # Publish the Podspec (if we're building a tag)
  #################
  - label: "⬆️ Publish Podspec"
    key: "publish"
    command: .buildkite/publish-pod.sh
    env: *common_env
    plugins: *common_plugins
    depends_on:
      - "test_ios"
      - "test_macos"
      - "validate"
      - "lint"
      - "version_check"
    if: build.tag != null
