# frozen_string_literal: true

BUILD_FOLDER = File.join(__dir__, '.build')
BUILD_LOG_PATH = File.join(BUILD_FOLDER, 'logs')
DERIVED_DATA_PATH = File.join(BUILD_FOLDER, 'derived-data')
PROJECT_PATH = File.join(__dir__, 'TracksDemo', 'TracksDemo.xcodeproj')

default_platform(:ios)

lane :open_demo_project do
  sh 'open -a /Applications/Xcode.app ../TracksDemo/TracksDemo.xcodeproj'
end

platform :ios do
  desc 'Builds the project and runs tests'
  lane :test do
    run_tests(
      scheme: 'TracksDemo',
      project: PROJECT_PATH,
      devices: ['iPhone 11'],
      deployment_target_version: '14.5',
      prelaunch_simulator: true,
      buildlog_path: BUILD_LOG_PATH,
      derived_data_path: DERIVED_DATA_PATH
    )
  end
end

platform :mac do
  desc 'Builds the project and runs tests'
  lane :test do
    run_tests(
      scheme: 'TracksDemo Mac',
      project: PROJECT_PATH,
      buildlog_path: BUILD_LOG_PATH,
      derived_data_path: DERIVED_DATA_PATH
    )
  end
end
