# frozen_string_literal: true

default_platform(:ios)

platform :ios do
  desc 'Builds the project and runs tests'
  lane :test do
    run_tests(
      scheme: 'Automattic-Tracks-iOS',
      devices: ['iPhone 11'],
      deployment_target_version: '14.5',
      prelaunch_simulator: true,
      buildlog_path: File.join(__dir__, '.build', 'logs'),
      derived_data_path: File.join(__dir__, '.build', 'derived-data')
    )
  end
end

platform :mac do
  desc 'Builds the project and runs tests'
  lane :test do
    run_tests(
      scheme: 'Automattic-Tracks-OSX',
      buildlog_path: File.join(__dir__, '.build', 'logs'),
      derived_data_path: File.join(__dir__, '.build', 'derived-data')
    )
  end
end
